language: node_js
node_js:
  - 12

services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh > wait-for-it.sh
  - chmod 754 wait-for-it.sh
  - docker-compose up --detach
  - ./wait-for-it.sh localhost:${API_PORT}

script:
  - docker-compose exec api yarn test
