version: '3'
services:
  api:
    build: api
    depends_on:
      - db
    env_file: .env
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - ./api:/api

  db:
    image: postgres:12-alpine
    restart: always
