version: '3'
services:
  api:
    build: .
    depends_on:
      - db
      - test_db
    env_file: .env
    ports:
      - '${API_PORT}:${API_PORT}'
    volumes:
      - .:/api

  db:
    image: postgres:12-alpine
    restart: always

  test_db:
    image: postgres:12-alpine
    restart: always
